import type { DisplayCard, DashboardIconName } from "./types";

export const TOKEN_STORAGE_KEY = "life_os_token";

export const CATEGORY_TABS = [
  "Tous les agents",
  "Informations",
  "Productivite",
  "Bien-etre",
  "Developpement",
  "Finance",
  "Creativite",
  "Social",
] as const;

export const NAV_ITEMS: Array<{ label: string; icon: DashboardIconName }> = [
  { label: "Accueil", icon: "home" },
  { label: "Mes agents", icon: "agents" },
  { label: "Scenarios", icon: "scenario" },
  { label: "Tableaux de bord", icon: "boards" },
  { label: "Donnees", icon: "database" },
  { label: "Calendrier", icon: "calendar" },
  { label: "Messages", icon: "message" },
  { label: "Automatisations", icon: "automation" },
  { label: "Integrations", icon: "integration" },
  { label: "Parametres", icon: "settings" },
];

export const CARD_BLUEPRINTS: DisplayCard[] = [
  {
    key: "weather",
    title: "METEO",
    badge: "Actif",
    state: "active",
    family: "weather",
    cta: "Previsions detaillees",
    accent: "cyan",
    description: "Conditions locales et recommandations",
  },
  {
    key: "news",
    title: "NEWS",
    badge: "Actif",
    state: "active",
    family: "news",
    cta: "Voir les articles",
    accent: "violet",
    description: "A la une et veille personnalisee",
  },
  {
    key: "productivity",
    title: "DEVELOPPEMENT PERSONNEL",
    badge: "Actif",
    state: "active",
    family: "productivity",
    cta: "Voir mes objectifs",
    accent: "green",
    description: "Execution, focus et repository",
  },
  {
    key: "project",
    title: "SUIVI DE PROJET",
    badge: "A connecter",
    state: "standby",
    family: "project",
    cta: "Ouvrir le projet",
    accent: "cyan",
    description: "Project Nova et avancement global",
  },
  {
    key: "health",
    title: "SANTE",
    badge: "A connecter",
    state: "standby",
    family: "health",
    cta: "Voir le tableau de bord",
    accent: "pink",
    description: "Score bien-etre, sommeil et activite",
  },
  {
    key: "finance",
    title: "FINANCES",
    badge: "A connecter",
    state: "standby",
    family: "finance",
    cta: "Voir l'analyse",
    accent: "green",
    description: "Depenses et budget du mois",
  },
  {
    key: "agenda",
    title: "AGENDA",
    badge: "A connecter",
    state: "standby",
    family: "agenda",
    cta: "Ouvrir l'agenda",
    accent: "cyan",
    description: "Rythme de la journee et rendez-vous",
  },
  {
    key: "learning",
    title: "APPRENTISSAGE",
    badge: "En veille",
    state: "standby",
    family: "learning",
    cta: "Continuer",
    accent: "violet",
    description: "Cours, progression et objectifs",
  },
  {
    key: "creative",
    title: "CREATIVITE",
    badge: "Actif",
    state: "active",
    family: "creative",
    cta: "Explorer",
    accent: "pink",
    description: "Idees et explorations visuelles",
  },
  {
    key: "social",
    title: "RELATIONS",
    badge: "En veille",
    state: "standby",
    family: "social",
    cta: "Voir mes contacts",
    accent: "violet",
    description: "Rappels relationnels et priorites",
  },
];
